services:
  jekyll:
    image: amirpourmand/al-folio
    container_name: al-folio-website
    platform: linux/amd64
    command: bash -c "
      rm -f Gemfile.lock
      && bundle install
      && bundle exec jekyll serve --watch --force_polling --port=8080 --host=0.0.0.0 --livereload --livereload-port=35729 --trace"
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
